name: biddt
description: Biddt - Premium Mobile Bidding Marketplace
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  firebase_messaging: ^14.7.10
  firebase_analytics: ^10.8.0
  
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Navigation
  go_router: ^12.1.3
  
  # UI
  google_fonts: ^6.1.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  intl: ^0.18.1
  
  # Utils
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.2
  
  # Icons
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  
  # QR Code
  qr_flutter: ^4.1.0
  
  # Animations
  confetti: ^0.7.0
  
  # Charts
  fl_chart: ^0.66.0
  
  # Image Picker
  image_picker: ^1.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/
